- name: Configure system
  hosts: localhost
  gather_facts: false
  vars:
    os_name: arch
    touchpad: SynPS/2 Synaptics TouchPad
    laptop_monitor: eDP1
    wlan_interface: wlan0
    ethernet_interface: eno1
  connection: local
  roles:
    - role: dotfiles
      tags: dotfiles
    - role: zsh
      tags:
        - dotfiles
        - zsh
