- name: Configure system
  hosts: localhost
  gather_facts: false
  vars:
    touchpad: DELL08E1:00 06CB:CD97 Touchpad
  connection: local
  roles:
    - role: ubuntu
      tags: ubuntu
    - role: dotfiles
      tags: dotfiles
