- name: Configure system
  hosts: localhost
  gather_facts: false
  vars:
    os_name: ubuntu
    touchpad: DELL08E1:00 06CB:CD97 Touchpad
    laptop_monitor: eDP-1
    wlan_interface: wlo1
    ethernet_interface: wlo1
    battery: BAT0
    battery_adapter: AC
  connection: local
  roles:
    - role: ubuntu
      tags: ubuntu
    - role: dotfiles
      tags: dotfiles
