- name: Configure system
  hosts: localhost
  gather_facts: false
  vars:
    os_name: arch
    touchpad: SynPS/2 Synaptics TouchPad
  connection: local
  roles:
    - role: dotfiles
      tags: dotfiles
