- name: Copy templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: sotiris
    group: sotiris
    mode: "{{ item.mode }}"
  loop:
    - { src: bspwmrc, dest: ~/.config/bspwm/bspwmrc, mode: "0744" }
    - { src: aliases, dest: ~/.config/shell/aliases, mode: "0644" }
    - { src: polybar/config.ini, dest: ~/.config/polybar/config.ini, mode: "0644" }

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: sotiris
    group: sotiris
    mode: "{{ item.mode }}"
  loop:
    - { src: repoman, dest: ~/.local/bin/repoman, mode: "0775" }
    - { src: env, dest: ~/.config/shell/common, mode: "0644" }
