- name: Copy templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: sotiris
    group: sotiris
    mode: 0744
  loop:
    - { src: bspwmrc, dest: ~/.config/bspwm/bspwmrc }

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: sotiris
    group: sotiris
    mode: 0775
  loop:
    - { src: repoman, dest: ~/.local/bin/repoman }
