- name: Copy templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: sotiris
    group: sotiris
    mode: "{{ item.mode }}"
  loop:
    - { src: bspwmrc, dest: ~/.config/bspwm/bspwmrc, mode: "0744" }
    - { src: sxhkdrc, dest: ~/.config/sxhkd/sxhkdrc, mode: "0775" }
    - { src: aliases, dest: ~/.config/shell/aliases, mode: "0644" }
    - { src: polybar/config.ini, dest: ~/.config/polybar/config.ini, mode: "0644" }
    - { src: alacritty/alacritty.yml, dest: ~/.config/alacritty/alacritty.yml, mode: "0644" }
    - { src: repoman, dest: ~/.local/bin/repoman, mode: "0775" }

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: sotiris
    group: sotiris
    mode: "{{ item.mode }}"
  loop:
    - { src: profile, dest: ~/.config/shell/profile, mode: "0644" }
    - { src: tmux.conf, dest: ~/.config/tmux/tmux.conf, mode: "0644" }
