#!/bin/sh

# File managing
alias cp='cp -v'
alias mv='mv -v'
alias rm='rm -v'
alias ls='ls --color=auto'
alias lsd='ls --color=auto -alh'
alias lsl='ls --color=auto -lh'

alias htop='htop --tree'

alias rp='. repoman'
alias find-node-modules='find . -name 'node_modules' -prune'
alias myip='curl ifconfig.co/'
alias vim='nvim'
alias todo='nvim ~/.local/share/todo'
alias du='du -h'
alias diff='diff --color=auto'
alias k='kubectl'
alias nvm-on='[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'

# Git
alias lg='lazygit'
alias gb='git branch'
alias gc='git checkout'
