#!/bin/sh

# Application preferences

export EDITOR=nvim
export TERMINAL=alacritty
export BROWSER=firefox
export FZF_DEFAULT_OPS='--layout=reverse -i'
export PASSWORD_STORE_DIR="$HOME/.local/share/password-store"
export NVM_DIR="$HOME/.config/nvm"
export NPM_CONFIG_USERCONFIG="$HOME/.config/npm/npmrc"
export PNPM_HOME="$HOME/.local/share/pnpm"
export CARGO_HOME="$HOME/.local/share/cargo"
export GOPATH="$HOME/.local/go"

# Path

if [[ -z $TMUX ]]; then
	export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
	export PATH="$HOME/.local/go/bin:$PATH"
fi
