- name: Copy zsh config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: sotiris
    group: sotiris
    mode: "{{ item.mode }}"
  loop:
    - { src: zprofile, dest: ~/.config/zsh/.zprofile, mode: "0644" }
    - { src: zshenv, dest: ~/.zshenv, mode: "0644" }
    - { src: zshrc, dest: ~/.config/zsh/.zshrc, mode: "0644" }
    - { src: scripts/completion.zsh, dest: ~/.config/zsh/scripts/completion.zsh, mode: "0644" }

- name: Create directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: "0755"
  loop:
    - ~/.config/zsh/plugins
    - ~/.config/zsh/scripts

- name: Install plugins
  ansible.builtin.git:
    repo: git@github.com:zsh-users/zsh-syntax-highlighting.git
    dest: ~/.config/zsh/plugins/zsh-syntax-highlighting
    depth: 1
    version: 0.7.1
  diff: false
