#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 3
bspc config window_gap 0

bspc config focused_border_color "#000000"
bspc config active_border_color  "#00ff00"
bspc config normal_border_color  "#444444"

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Background
feh --bg-fill $HOME/Pictures/Wallpaper/gruvbox_linux_resized.png

# Add greek keyboard layout
setxkbmap us,gr -option grp:alt_shift_toggle

# Use caps lock key as ctrl key
setxkbmap -option ctrl:nocaps

# Launch polybar
killall polybar ; polybar --config=$HOME/.config/polybar/config.ini laptop &

# Enable tapping on touchpad
xinput set-prop "{{ touchpad }}" "libinput Tapping Enabled" 1
xinput set-prop "{{ touchpad }}" "libinput Natural Scrolling Enabled" 1

# Keyboard rate
xset r rate 230 45

# Fix cursor X on wallpaper
xsetroot -cursor_name left_ptr &

# ~/.local/bin/startup
# ~/.config/polybar/launch.sh
# flameshot &
